--HAD TROUBLE WITH THE DELIMITER
--IF THE FILE IS IMPORTED, THE DELIMITER CAUSES PROBLEMS
--IF THE TRIGGERS ARE ENTERED VIA TERMINAL (SPECIFYING THE DELIMITER NOT BE ';') THERE DOESN'T SEEM TO BE ANY ISSUE
--FROM LOOKING ONLINE, THE PROBLEM WITH IMPORTING IS DUE TO PHPMYADMIN
DELIMITER //

--IF A WEAPON IS RENAMED IN WEAPONS, IT'S ALSO RENAMED IN STATS FOR CONSISTENCY 
CREATE TRIGGER renameWeapon
AFTER UPDATE ON weapons
FOR EACH ROW BEGIN
  UPDATE weapon_stats SET weapon_name=NEW.weapon_name 
		WHERE weapon_name=OLD.weapon_name;
END;

--IF AN APPAREL IS RENAMED IN APPAREL, IT'S ALSO RENAMED IN STATS FOR CONSISTENCY
CREATE TRIGGER renameApparel
AFTER UPDATE ON apparel
FOR EACH ROW BEGIN
  UPDATE apparel_stats SET apparel_name=NEW.apparel_name 
		WHERE apparel_name=OLD.apparel_name;
END;

--IF A WEAPON IS DROPPED, SO IS ALL THE AMMO FOR THAT WEAPON
CREATE TRIGGER dropAmmo 
AFTER DELETE ON weapon_stats 
FOR EACH ROW BEGIN 
	IF OLD.weapon_type = ammo.weapon_type THEN 
		UPDATE ammo 
		SET quantity = 0; 
	END IF; 
END;

--IF AN ITEM OF APPAREL IS DROPPED, AND IT IS EQUIPPED, UNEQUIP IT
CREATE TRIGGER droppingEquippedApparel
AFTER DELETE ON apparel
FOR EACH ROW BEGIN 
	IF OLD.apparel_name = player.equippedHeadwear THEN 
		UPDATE player
		SET equippedHeadwear = NULL; 
	END IF;
    IF OLD.apparel_name = player.equippedArmor THEN 
		UPDATE player
		SET equippedHArmor = NULL; 
	END IF;
END;
//
